### PR TITLE
Declare logback as optional dependency

### PR DESCRIPTION
**Pull request by sbesson**
Companion to https://github.com/ome/bioformats/pull/3886 and https://github.com/ome/ome-common-java/pull/68

See https://github.com/ome/bioformats/pull/3886#pullrequestreview-1223229491 for the rationale

### CODE REVIEW

**Comment by jburel** [comment]
it looks like this change leads to an error in omero-blitz build
see https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-build-build/1421/console

**Comment by sbesson** [comment]
Interesting, thanks for reporting. Looks like `omero-blitz` has an explicit dependency on `logback-classic`. I can either open an `omero-blitz` PR declaring the dependency or we can exclude this PR for now. Either way, if `logback` is truly declared optional in Bio-Formats 6.12.0, we will need this dependency handled at the OMERO level /cc @dgault

**Comment by jburel** [comment]
I have prepared a PR for omero-blitz

**Comment by sbesson** [comment]
See https://github.com/ome/omero-blitz/pull/133

**Comment by jburel** [comment]
see also https://github.com/ome/omero-insight/pull/337

**Review by dgault — APPROVED** [review]

**Pull request merged**
